### ISSUE TITLE
GenreDataLoader remove_outliers()

### ISSUE THREAD

**Issue by tgj505** [fox-daniel/Genre#6]
## remove_outliers() data

Hi! 

When I use the `LoadGenreData` class and call the `.data` function, I'm able to use other functions like `.get_list_of_genres()`. When I use the `remove_outliers` function, though, I get an **`AttributeError`** when trying to use the same functions. This also breaks if I try to use the `remove_outliers()` function on a `.data` type object.

Why this is confusing to me is that the resulting object of both the `.data` and `remove_outliers()` functions are of the same type, `<class 'pandas.core.frame.DataFrame'>`, And they both look the same when printing their `.head()`.

Let me know if this makes sense; I'm probably just missing something straightforward!

>`genre_data = LoadGenreData(now, X_path_train = X_path_train, y_path_train = y_path_train,
                                             X_path_test = X_path_test, y_path_test = y_path_test)`
>
>`data = genre_data.data`
>`no_outliers = genre_data.remove_outliers(30)`
>
>`artist_list = data.index.tolist()`
>`genre_list = genre_data.get_list_of_genres()`
>
>`no_outliers_artist = no_outliers.index.tolist()`
>`no_outliers_genre = no_outliers.get_list_of_genres()`
>
> AttributeError: 'DataFrame' object has no attribute 'get_list_of_genres'

The error message is given below:

>`Traceback (most recent call last):`
>`   File"C:/TomTests/daniel_project/artist_genres_edge_list_maker.py", line 40, in <module>`
>`    no_outliers_genre = no_outliers.get_list_of_genres()`
>`  File "C:\Program Files\Python37\lib\site-packages\pandas\core\generic.py", line 5180, in __getattr__ return object.__getattribute__(self, name)`
>`AttributeError: 'DataFrame' object has no attribute 'get_list_of_genres'`

**Comment by fox-daniel** [comment]
Hey,

There are two issues I see. 1) a syntax issue that is leading to an error. 2) a functionality issue.

1) .get_list_of_genres() is a method you can apply to an instance of the LoadGenreData class. So in the code quoted above, genre_data is an instance and you can apply .get_list_of_genres() to it. However, you try to apply it to no_outliers, which is not an instance: no_outliers = genre_data.remove_outliers(30) so no_outliers is just a DataFrame from which the outliers are removed. 

2) Functionality. Currently the class does not allow you to modify the underlying DataFrame in-place, except by adding columns with different forms of the genre lists (list, set, string). So you can't remove_outliers() and then get_list_of_genres() to get the list of genres after the outliers are removed. The remove_outliers() method returns a new view of the DataFrame. 

Do we need new functionality?

**Comment by tgj505** [comment]
This makes sense, thanks for the clear explanation! It's super useful for helping me understand the structure. I think the main issue was that I just misread my own code :( haha

**Comment by fox-daniel** [comment]
Let me know if we need more functionality.
